import { describe,expect,it } from 'vitest';
import { createNewSave,createOwnedCharacter } from './save';
import { boostRemainingLabel,grantSandboxDiamonds,pauseTimedBoosts,purchaseProduct,resumeTimedBoosts,unlockedMagicSlotCount,useTimedBoost } from './commerce';

describe('commerce',()=>{
  it('grants sandbox diamonds once and records purchases',()=>{let save={...createNewSave(1),party:[createOwnedCharacter('beowulf_young')]};save=grantSandboxDiamonds(save);save=grantSandboxDiamonds(save);expect(save.commerce?.diamonds).toBe(500);const result=purchaseProduct(save,'status_5');expect(result.ok).toBe(true);expect(result.save.commerce?.diamonds).toBe(476);expect(result.save.party[0].paidStatusPoints).toBe(5);expect(result.save.commerce?.purchaseHistory).toHaveLength(1)});
  it('enforces one-time purchases',()=>{let save=grantSandboxDiamonds(createNewSave(1));const first=purchaseProduct(save,'premium_pet');expect(first.ok).toBe(true);const second=purchaseProduct(first.save,'premium_pet');expect(second.ok).toBe(false);expect(first.save.pets?.[0].petId).toBe('star_fox')});
  it('extends timed boosts by 30 minutes',()=>{let save={...createNewSave(1),items:{exp_boost:2}};const first=useTimedBoost(save,'exp_boost',1000)!;const second=useTimedBoost(first,'exp_boost',2000)!;expect(second.commerce?.activeBoosts.expUntil).toBe(1000+60*60*1000);expect(second.items.exp_boost).toBe(0)});
  it('unlocks map-wide auto pickup only after purchase',()=>{const save=grantSandboxDiamonds(createNewSave(1));expect(save.commerce?.entitlements).not.toContain('auto_pickup');const bought=purchaseProduct(save,'auto_pickup');expect(bought.ok).toBe(true);expect(bought.save.commerce?.entitlements).toContain('auto_pickup')});
  it('keeps quick slots and extra magic slots locked until purchased',()=>{let save=grantSandboxDiamonds(createNewSave(1));expect(save.commerce?.entitlements).not.toContain('quick_slots_5');expect(unlockedMagicSlotCount(save)).toBe(1);const quick=purchaseProduct(save,'quick_slots_5');expect(quick.ok).toBe(true);expect(quick.save.commerce?.entitlements).toContain('quick_slots_5');const second=purchaseProduct(quick.save,'magic_slot_2');expect(second.ok).toBe(true);expect(unlockedMagicSlotCount(second.save)).toBe(2);const third=purchaseProduct(second.save,'magic_slot_3');expect(third.ok).toBe(true);expect(unlockedMagicSlotCount(third.save)).toBe(3)});
  it('does not charge for an item bundle beyond the 99 item cap',()=>{const funded=grantSandboxDiamonds({...createNewSave(1),items:{exp_boost:95}});const result=purchaseProduct(funded,'exp_boost_10');expect(result.ok).toBe(false);expect(result.save.commerce?.diamonds).toBe(500);expect(result.save.items.exp_boost).toBe(95)});
  it('pauses active boost countdown while a popup is open',()=>{let save=createNewSave(1);save={...save,commerce:{...save.commerce!,activeBoosts:{expUntil:11_000,dropUntil:0}}};const paused=pauseTimedBoosts(save,1_000);const resumed=resumeTimedBoosts(paused,6_000);expect(resumed.commerce?.activeBoosts.expUntil).toBe(16_000);expect(resumed.commerce?.activeBoosts.expPausedAt).toBeUndefined()});
  it('formats boost duration using the specification units',()=>{expect(boostRemainingLabel(59_000,0)).toBe('59s');expect(boostRemainingLabel(61_000,0)).toBe('2m');expect(boostRemainingLabel(3_601_000,0)).toBe('2h');expect(boostRemainingLabel(90_000_000,0)).toBe('2d')});
});
